
# If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: inventif
email: remy.maucourt@yahoo.fr
description: >
  Site personnel de Rémy Maucourt: Fablab, code, sculptures lumineuses et expérimentations diverses.
baseurl: ''
url: "https//www.inventif.fr"

github_page: https://github.com/Ruff9
linkedin: https://www.linkedin.com/in/remymaucourt/
open_processing: https://www.openprocessing.org/user/158204#sketches

disqus:
  shortname: inventif9

excerpt_separator: <!--more-->

lang: fr
date_format: "%-d %B %Y"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
