
# If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Inventif
email: your-email@example.com
description: >
  Expérimentations
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://inventif.fr"
twitter_username: jekyllrb
github_username:  jekyll
excerpt_separator: <!--more-->

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
